WITH CANCLED AS (
    SELECT APNT_NO, PT_NAME, P.PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
    FROM PATIENT P
    JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
    WHERE A.APNT_CNCL_YN = 'N'
)

SELECT APNT_NO, PT_NAME, PT_NO, C.MCDP_CD, DR_NAME, APNT_YMD
FROM CANCLED C
JOIN DOCTOR D ON C.MDDR_ID = D.DR_ID
WHERE C.APNT_YMD LIKE('%2022-04-13%') AND C.MCDP_CD = 'CS'
ORDER BY C.APNT_YMD ASC