SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) > 0
ORDER BY ID ASC


# # 틀린코드
# SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM SKILLCODES S
# JOIN DEVELOPERS D ON S.CODE = D.SKILL_CODE
# WHERE CONV(D.SKILL_CODE, 10, 2) & (
#     SELECT SUM(CONV(S.CODE, 10, 2))
#     FROM SKILLCODES S
#     WHERE S.CATEGORY = 'Front End'
# ) > 0
# ORDER BY D.ID ASC

