WITH FOODGROUP AS (
    SELECT *, MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
)

SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOODGROUP
WHERE PRICE = MAX_PRICE
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC